# Generated by Django 4.2.10 on 2024-02-21 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_manager", "0002_project_delete_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="content",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="author",
            new_name="owner",
        ),
        migrations.RemoveField(
            model_name="project",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateTimeField(default="2024-03-15"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("To do", "To do"),
                            ("In progress", "In progress"),
                            ("Done", "Done"),
                        ],
                        default="To do",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.project",
                    ),
                ),
            ],
        ),
    ]
