# Generated by Django 4.2.10 on 2024-02-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0005_note_delete_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_by",
            new_name="owner",
        ),
    ]
