# Generated by Django 4.2.10 on 2024-02-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_manager", "0007_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="task",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="owned_by",
            new_name="assigned_to",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="owner",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="note",
            name="author",
        ),
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_author",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
