# Generated by Django 4.2.10 on 2024-02-28 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_manager",
            "0008_rename_task_note_note_rename_owner_profile_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_creation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
