# Generated by Django 4.2.10 on 2024-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0014_remove_note_message_note_task_alter_note_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
