# Generated by Django 4.2.10 on 2024-03-04 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0015_profile_title_delete_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="title",
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
