# Generated by Django 4.2.10 on 2024-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0017_remove_profile_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
