# Generated by Django 4.2.10 on 2024-03-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0018_profile_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="title",
            new_name="job_title",
        ),
    ]
