# Generated by Django 4.2.10 on 2024-03-05 05:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0019_rename_title_profile_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
